GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< https://www.youtube.com/watch?v=PWj-70ZsWVc
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/5fed26f3-dafa-48db-a862-6010b2910f7b/transcription
Content-Type:  application/json

{
  "prompt": "programa rocketseat one"
}